<?php
// This file is generated by Composer
$loader = require 'vendor/autoload.php';
$loader->add('AppName', __DIR__.'/../src/');

$client = new \Gitlab\Client('https://gitlab.com/api/v3/');
if ( isset($token) )
  $client->authenticate($token, \Gitlab\Client::AUTH_URL_TOKEN);

$parser = new \cebe\markdown\GithubMarkdown();

// Make robust the way to find the css and the js. The handler can be on many directorys.
$relative_path = explode( ',', $this->GetConfigValue('action_path'));
// If nothing works try with this very basic prism.
$prims_css_default = "https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism.min.css";
$prims_js_default = "https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/prism.min.js";
// Check for the css and the js files. If exist overwrite the black/withe web.
foreach ($relative_path as $key => $value) {
  if (is_file($relative_path[$key].'/gitlab/prism.css') && is_file($relative_path[$key].'/gitlab/prism.js'))
  {
    $prims_css_default = $relative_path[$key].'/gitlab/prism.css';
    $prims_js_default = $relative_path[$key].'/gitlab/prism.js';
  }
}

// TODO ask to use and put this on the header.php. (head html) Maybe this dont work on very old browers becose of this.
echo '<link rel="stylesheet" type="text/css" href="'.$prims_css_default.'" />';
echo '<script src="'.$prims_js_default.'"></script>';

if ( isset($repo_id) && isset($path) ){
  $git_repo = $repo_id;
  $git_path = $path;
} else {
  $git_repo = "2135786";
  $git_path = "README.md";
}

$api = "repo";
$reference = "master";

try {
  $readme = $client->api('repositories')->getFile( $git_repo, $git_path, $reference);
  echo $parser->parse( base64_decode($readme['content']) );
}catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

// TODO: The default option is bring the Readme, for the newer versions gonna to get all git repo info.
//echo json_encode($readme, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
?>
